-- CreateEnum
CREATE TYPE "TipoFato" AS ENUM ('ATIVO_CIRCULANTE', 'ATIVO_NAO_CIRCULANTE', 'ATIVO_PERMANENTE', 'PASSIVO_CIRCULANTE', 'PASSIVO_EXIGIVEL', 'PATRIMONIO_LIQUIDO', 'DESPESAS_OPERACIONAIS', 'DESPESAS_NAO_OPERACIONAIS', 'RECEITAS_OPERACIONAIS', 'RECEITAS_NAO_OPERACIONAIS');

-- CreateTable
CREATE TABLE "Despesas" (
    "id" TEXT NOT NULL,
    "tipo" TEXT NOT NULL,
    "valor" DECIMAL(65,30) NOT NULL,
    "descricao" TEXT,
    "dataRegistro" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dataInicio" TIMESTAMP(3) NOT NULL,
    "dataFim" TIMESTAMP(3),

    CONSTRAINT "Despesas_pkey" PRIMARY KEY ("id")
);
